# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GDDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GDDemo
    pod 'Charts'
    pod 'SnapKit'
    pod 'MJRefresh'
    pod 'AliPlayerSDK_iOS'
    pod 'WebViewJavascriptBridge', '~> 6.0'
    pod 'CocoaAsyncSocket'

end
